/**********************************************************************************/
/* Class Name    : ET_SingleSend_ContHandler                                           */
/* Purpose       : Creates the List of Send Definition Records needed to create the ESD in Exact Target
/* Created By    : Cognizant Technology Solutions                                 */
/**********************************************************************************/
public class ET_SingleSend_ContHandler{
    
      }